version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:15.0.1
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install --yes ant
      - run: ant -propertyfile circleci-build.properties
